### ISSUE TITLE
dynamic retrival of cryptocurrency list

### ISSUE THREAD

**Issue by LegendOfGIT** [lukechilds/coinlist#2]
Replace the static list of cryptocurrencies (coins.json) with a retrival from
https://coinmarketcap.com/all/views/all/

;)

**Comment by lukechilds** [comment]
It's intentionally designed to be a static document with live data removed to allow for:

- Offline use
- Embedding in applications
- Parsing the raw JSON
- Instant access, no need to wait for an async operation

If you just want the latest information from the API then this package isn't for you, you should call the API directly:

```js
fetch('https://api.coinmarketcap.com/v1/ticker/?limit=0')
```
